FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

# Instalează toate pachetele de care ai nevoie
RUN pip install --no-cache-dir \
    black \
    isort \
    requests \
    pandas \
    python-dotenv \
    tabulate
